[project]
name = "backend"
version = "0.8.3"
description = "Default template for PDM package"
authors = [
    {name = "xevansz", email = "minithbmatthew@gmail.com"},
]
dependencies = [
    "black",
    "isort",
    "ruff",
    "flake8",
    "pre-commit",
    "fastapi[standard]>=0.128.7",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
